//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1215.0 using the following command:
// xscgen -n PlayerApp.XML sequence.xsd
namespace PlayerApp.XML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1215.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("videoType", Namespace="http://sequencemovieplayer.antanysavage.it/sequences/schema")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("video", Namespace="http://sequencemovieplayer.antanysavage.it/sequences/schema")]
    public partial class VideoType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("path")]
        public string Path { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("duration")]
        public float Duration { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Duration property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DurationSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("start")]
        public string Start { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("end")]
        public string End { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("from")]
        public string From { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("to")]
        public string To { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("daysOfWeek")]
        public string DaysOfWeek { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("remotePath")]
        public string RemotePath { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("limited")]
        public int Limited { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Limited property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LimitedSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _group = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlAttributeAttribute("group")]
        public string Group
        {
            get
            {
                return _group;
            }
            set
            {
                _group = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public AcceptedVideoTypes Type { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Type property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1215.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("acceptedVideoTypes", Namespace="http://sequencemovieplayer.antanysavage.it/sequences/schema")]
    public enum AcceptedVideoTypes
    {
        
        Video,
        
        HiddenWindow,
        
        BlackWindow,
        
        Watch,
        
        Photo,
        
        Browser,
        
        Weather,
        
        [System.Xml.Serialization.XmlEnumAttribute("FTPVideo")]
        FtpVideo,
        
        [System.Xml.Serialization.XmlEnumAttribute("FTPImage")]
        FtpImage,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1215.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sequenceType", Namespace="http://sequencemovieplayer.antanysavage.it/sequences/schema")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("sequence", Namespace="http://sequencemovieplayer.antanysavage.it/sequences/schema")]
    public partial class SequenceType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VideoType> _videos;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlArrayAttribute("videos")]
        [System.Xml.Serialization.XmlArrayItemAttribute("video", Namespace="http://sequencemovieplayer.antanysavage.it/sequences/schema")]
        public System.Collections.ObjectModel.Collection<VideoType> Videos
        {
            get
            {
                return _videos;
            }
            private set
            {
                _videos = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SequenceType" /> class.</para>
        /// </summary>
        public SequenceType()
        {
            this._videos = new System.Collections.ObjectModel.Collection<VideoType>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("remotePath")]
        public string RemotePath { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1215.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("videosType", Namespace="http://sequencemovieplayer.antanysavage.it/sequences/schema")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("videos", Namespace="http://sequencemovieplayer.antanysavage.it/sequences/schema")]
    public partial class VideosType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VideoType> _video;
        
        [System.Xml.Serialization.XmlElementAttribute("video")]
        public System.Collections.ObjectModel.Collection<VideoType> Video
        {
            get
            {
                return _video;
            }
            private set
            {
                _video = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Video collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VideoSpecified
        {
            get
            {
                return (this.Video.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VideosType" /> class.</para>
        /// </summary>
        public VideosType()
        {
            this._video = new System.Collections.ObjectModel.Collection<VideoType>();
        }
    }
}
